"""empty message

Revision ID: 238cb951b6b8
Revises: 99ec27f2b760
Create Date: 2020-12-09 09:59:11.433232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '238cb951b6b8'
down_revision = '99ec27f2b760'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lifesense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mid', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mid'], ['member.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_lifesense_created_at'), 'lifesense', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lifesense_created_at'), table_name='lifesense')
    op.drop_table('lifesense')
    # ### end Alembic commands ###
