"""empty message

Revision ID: 664cc11f0d54
Revises: 238cb951b6b8
Create Date: 2020-12-12 20:20:34.549865

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '664cc11f0d54'
down_revision = '238cb951b6b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_member_created_at', table_name='member')
    op.drop_table('member')
    op.drop_index('ix_lifesense_created_at', table_name='lifesense')
    op.drop_index('phone', table_name='lifesense')
    op.drop_table('lifesense')
    op.drop_constraint('netease_ibfk_1', 'netease', type_='foreignkey')
    op.drop_column('netease', 'mid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('netease', sa.Column('mid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('netease_ibfk_1', 'netease', 'member', ['mid'], ['id'])
    op.create_table('lifesense',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('mid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('phone', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('status', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['mid'], ['member.id'], name='lifesense_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('phone', 'lifesense', ['phone'], unique=True)
    op.create_index('ix_lifesense_created_at', 'lifesense', ['created_at'], unique=False)
    op.create_table('member',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('tel', mysql.VARCHAR(length=11), nullable=True),
    sa.Column('nickname', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('headimgurl', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('mp_openid', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('min_openid', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('unionid', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('status', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_member_created_at', 'member', ['created_at'], unique=False)
    # ### end Alembic commands ###
