"""empty message

Revision ID: 99ec27f2b760
Revises: 0de11cd433cd
Create Date: 2020-12-03 09:09:04.890725

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '99ec27f2b760'
down_revision = '0de11cd433cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('netease_tasks', sa.Column('nid', sa.Integer(), nullable=True))
    op.drop_constraint('netease_tasks_ibfk_1', 'netease_tasks', type_='foreignkey')
    op.create_foreign_key(None, 'netease_tasks', 'netease', ['nid'], ['id'])
    op.drop_column('netease_tasks', 'uid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('netease_tasks', sa.Column('uid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'netease_tasks', type_='foreignkey')
    op.create_foreign_key('netease_tasks_ibfk_1', 'netease_tasks', 'netease', ['uid'], ['id'])
    op.drop_column('netease_tasks', 'nid')
    # ### end Alembic commands ###
