"""empty message

Revision ID: 9e4bbb30f2e8
Revises: c496e334cbaf
Create Date: 2020-11-30 15:53:21.697255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e4bbb30f2e8'
down_revision = 'c496e334cbaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('netease_tasks', sa.Column('messages', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('netease_tasks', 'messages')
    # ### end Alembic commands ###
