"""empty message

Revision ID: c496e334cbaf
Revises: fc3a8365b89e
Create Date: 2020-11-30 15:44:00.004045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c496e334cbaf'
down_revision = 'fc3a8365b89e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('netease', sa.Column('messages', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('netease', 'messages')
    # ### end Alembic commands ###
