"""empty message

Revision ID: fc3a8365b89e
Revises: b1d36b1c1a35
Create Date: 2020-11-25 22:08:39.960233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc3a8365b89e'
down_revision = 'b1d36b1c1a35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'netease', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'netease', type_='unique')
    # ### end Alembic commands ###
